config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pets
  resources :parks

  authenticated do
    root :to => 'pets#index', as: :authenticated
  end

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :user
  geocoded_by :address

  after_validation :geocode, :if => :address_changed?
  validates :address, presence: true, uniqueness: true
  validates_presence_of :details

  paginates_per 8

  SEARCH_RADIUS = 50
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_attached_file :pic, styles: { larger: "650x220>", medium: "150x98", thumb: "100x100>" }

  validates :name,  presence: true, length: { maximum: 50 }
  validates_attachment_size :pic, less_than: 2.megabyte
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pets
  has_many :parks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, raise: false

  def index
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  def index
    if params[:search].present?
      @parks = Park.near(params[:search]).page params[:page]
    else
      @parks = Park.order('created_at DESC').page params[:page]
    end
  end

  def show
    @park = Park.find(params[:id])
  end

  def new
    @park = Park.new
  end

  def create
    @park = current_user.parks.build(park_params)

    if @park.save
      redirect_to park_path(@park), notice: "This park has been added!"
    else
      flash.now[:alert] = "Unable to add this park"
      render 'new'
    end
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])
    @park.user == current_user

    if @park.update_attributes(park_params)
      redirect_to park_path(@park), notice: "Park Updated"
    else
      flash.now[:alert] = "Unable to update park"
      render 'edit'
    end
  end

  def destroy
    @park = Park.find(params[:id])
    @park.destroy
    redirect_to parks_path, notice: "Park Removed"
  end

  private

  def park_params
    params.require(:park).permit(:address, :details, :longitude, :latitude)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pets = current_user.pets
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(pet_params)
    @pet.user = current_user

    if @pet.save
      redirect_to pet_path(@pet), notice: "Your pet has been added!"
    else
      flash.now[:alert] = "Unable to add your pet"
      render 'new'
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])

    if @pet.update_attributes(pet_params)
      redirect_to pets_path, notice: "Pet Updated"
    else
      flash.now[:alert] = "Unable to update your pet"
      render 'edit'
    end
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path, notice: "Pet Removed"
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :birthday, :sex, :breed, :description, :pic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pet_helper.rb
module PetHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1> Welcome to PetPals! </h1>
  <h4>Where you're best friend can make some more pals!</h4>

  <%= image_tag("petpals.jpg", :class => "petpal") %>

  <% if user_signed_in? %>
    <%# <%= link_to "Add a Pet",new_pet_path %1> %>
  <% else %>
  <%= link_to "Sign up today!", new_user_registration_path, :class => "btn" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petpals</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1 class="logo">Pet<i class="fa fa-paw" aria-hidden="true"></i>Pals</h1>
      <% end %>

      <nav class="navbar-right">
        <% if user_signed_in? %>
          <p>Logged in as <strong><%= current_user.email %></strong></p>
          <%= link_to 'Edit profile', edit_user_registration_path %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>

        <% else %>
          <%= link_to "Register", new_user_registration_path %>
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </nav>
    </header>

    <% if notice %>
      <div class="flash-container notice">
        <p class="flash"><%= notice %></p>
      </div>
    <% end %>

    <% if alert %>
      <div class="flash-container alert">
        <p class="flash"><%= alert %></p>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/parks/_form.html.erb
<%= form_for(@park) do |f| %>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, :placeholder => "A pet friendly Park!" %>

    <%= f.label :details %>
    <%= f.text_field :details, :placeholder => "Give a small description of the park. Is it enclosed? Is there a leash-less area?" %>

    <div class="action">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/parks/_park.html.erb
<%= link_to park_path(park), :class => "park-container" do %>
  <div class="park">
    <h4><%= park.address %></h4>
    <p>0 users have visited</p>
    <p>0 pet have favorited</p>
  </div>
<% end %>

app/views/parks/_results.html.erb
<div class="search-container">
  <div class="search">
    <%= form_tag(parks_path, method: :get) do %>
      <%= text_field_tag :search, params[:search],
        placeholder: "Search by City / Zip Code" %>
      <div class="actions">
        <%= submit_tag "Search Near", :name => nil %>
      </div>
    <% end %>
    <div class="add-park">
      <%= link_to "Add a park!", new_park_path %>
    </div>
  </div>
</div>

<div class="main">
  <div class="parks-container">
    <% if @parks.any? %>
      <%= render @parks %>
      <%= paginate @parks, left: 2, right: 2 %>
    <% else %>
      <div class="no-parks">
        <h4>No parks have been added yet!</h4>
      </div>
    <% end %>
  </div>

  <div class="map-container">
    <div id="map"></div>
    <script>
      function initMap() {
        var coords = <%= @parks.map { |park| { lat: park.latitude, lng: park.longitude} }.to_json.html_safe %>
        var bounds = new google.maps.LatLngBounds();

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 10,
          center: {lat: 39.8097, lng: 98.5556}
        });

        coords.forEach(function(coord) {
          console.log('put a pin on the map')

          var marker = new google.maps.Marker({
            position: coord,
            map: map
          });
          bounds.extend(coord);
          map.fitBounds(bounds);
        });
      }
    </script>

    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUsNggEpQlvX4THGB36KNsHWYYgi2SgXM&callback=initMap">
    </script>
  </div>
</div>

app/views/parks/_search.html.erb
<div class="full-search-container">
  <div class="search-full">
    <%= form_tag(parks_path, method: :get) do %>
      <h3>Search for parks in your area</h3>
      <%= text_field_tag :search, params[:search],
        placeholder: "Search by City / Zip Code" %>
      <div class="actions">
        <%= submit_tag "Search Near", :name => nil %>
      </div>
    <% end %>
  </div>
</div>

app/views/parks/edit.html.erb
<div class="container">
  <%= render 'shared/model_errors', model: @park %>

  <h1>Edit this Park</h1>
  <%= render 'parks/form' %>
</div>

app/views/parks/index.html.erb
<div class="index">
  <% if params[:search].present? %>
    <%= render 'results' %>
  <% else %>
    <%= render 'results' %>
  <% end %>
</div>

app/views/parks/new.html.erb
<div class="container">
  <%= render 'shared/model_errors', model: @park %>

  <h3>Add a park!</h3>
  <%= render 'parks/form' %>
</div>

app/views/parks/show.html.erb
<div class="container">
  <div class="top">
    <div class="alternate-actions">
    </div>

    <div class="actions">
      <% if @park.user == current_user %>
        <%= link_to "Edit", edit_park_path(@park) %>
        <%= link_to park_path(@park), class: "delete", method: :delete, data: {confirm: "Remove this park?"} do %>
          <i class="fa fa-times" aria-hidden="true" title="delete"></i>
        <% end %>
      <% end %>
  </div>
</div>

<div class="park-info">
  <h3 class="park-name"> <%= @park.address %></h3>
  <p class="park-details"><%= @park.details %></p>
</div>

<%= image_tag  "http://maps.googleapis.com/maps/api/staticmap?center=#{@park.latitude},#{@park.longitude}&markers=#{@park.latitude},#{@park.longitude}&zoom=14&size=650x250&key=AIzaSyA4BHW3txEdqfxzdTlPwaHsYRSZbfeIcd8",
  class: 'park-map'%>

<div class="bottom">
  <div class="bottom-left">
    <div class="nearby">
      <h4>Nearby Parks</h4>
      <% for park in @park.nearbys(10) %>
        <%= link_to park.address, park %> (<%= park.distance.round(2) %> miles)
      <% end %>
    </div>
  </div>

  <div class="bottom-right">
    <div class="other-info">
      <h4>Visits and Favorites</h4>
      <p>0 users have visited</p>
      <p>0 pet have favorited</p>
    </div>
  </div>
</div>
</div>

app/views/pets/_form.html.erb
<%= form_for @pet, html: { class: "pet-form", multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => "Your pet's name" %>

    <div class="field">
      <%= f.label :sex %>
      <%= f.select(:sex, [['Male', 'M'], ['Female', 'F']]) %>
    </div>

    <%= f.label :breed %>
    <%= f.text_field :breed, :placeholder => "Ex. My pet is a mix of Pit Bull and Boxer" %>

    <%= f.label :description %>
    <%= f.text_field :description, :placeholder => "Tell us about your pet!" %>

    <%= f.file_field :pic %>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/pets/_pet.html.erb
<%= link_to pet_path(pet), :class => "pet-container" do %>
  <div class="pet">
    <%= image_tag pet.pic.url(:medium), :class => "pet-pic" %>
  </div>

  <h4 class="name"><%= pet.name %></h4>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <%= render 'shared/model_errors', model: @pet %>

  <h1>Edit your Pet</h1>
  <%= render 'pets/form' %>
</div>

app/views/pets/index.html.erb
<div class="pets-container">
  <% if @pets.any? %>
    <h3>Your Pets!</h3>
    <%= render @pets %>
  <% else %>
    <div class="no-pets">
      <p>You haven't added a pet yet!</p>
    </div>
  <% end %>

  <div class="add-pet">
    <%= link_to new_pet_path do %>
      <span class="fa fa-plus" aria-hidden="true"></span>
      <p>Add a pet</p>
    <% end %>
  </div>
</div>

app/views/pets/new.html.erb
<h1>Add a Pet</h1>

<%= form_for(@pet) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :placeholder => "Your pet's name" %>

    <div class="field">
      <%= f.label :sex %>
      <%= f.select(:sex, [['Male', 'm'], ['Female', 'f']]) %>
    </div>

    <%= f.label :breed %>
    <%= f.text_field :breed, :placeholder => "Ex. My pet is a mix of Pit Bull and Boxer" %>

    <%= f.label :description %>
    <%= f.text_field :description, :placeholder => "Tell us about your pet!" %>

    <div class="button">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/pets/show.html.erb
<div class="pet-dash">
  <div class="top">
    <div class="alternate-actions">
      <%= link_to root_path do %>
        <i class="fa fa-caret-left" aria-hidden="true"></i>Back
      <% end %>
    </div>

    <div class="actions">
      <% if @pet.user = current_user %>
        <%= link_to "Edit", edit_pet_path %>
          <%= link_to pet_path(@pet), class: "delete", method: :delete, data: {confirm: "Remove this pet?"} do %>
            <i class="fa fa-times" aria-hidden="true" title="delete"></i>
          <% end %>
      <% end %>
    </div>
  </div>

  <div class="pic-container">
    <%= image_tag @pet.pic.url, :class => "pic" %>
  </div>

  <div class="pet-info">
    <h3 class="dash-name"><%= @pet.name %></h3>
    <p><%= @pet.sex.upcase %></p>
    <p><%= @pet.breed %></p>
    <p><%= @pet.description %></p>
    <p>Location</p>
  </div>

  <div class="park">
    Cocoa's favorate park
  </div>
</div>

app/views/shared/_model_errors.html.erb
<% if model.errors.full_messages.any? %>
  <% model.errors.full_messages.each do |error_message| %>
    <%= error_message %>
  <% end %>
<% end %>